name: Deploy

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    if: contains(toJson(github.event.commits), '[deploy]') == true
    name: Deploy Docker images
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Sets build date
        run: echo "BUILD_DATE=$(date '+%Y%m%d')" >> $GITHUB_ENV
      - name: Sets version to tag
        run: echo "BUILD_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build images
        run: PUSH=1 VERSION="${BUILD_VERSION}" BUILD_DATE=${BUILD_DATE} make build
