name: Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    name: Deploy Docker images
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Sets version to tag
        run: echo "BUILD_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build images
        run: PUSH=1 VERSION="${BUILD_VERSION}" make build
      # - name: Tag latest
      #   run: VERSION="${BUILD_VERSION}" make tag_latest
      # - name: Tag major/minor
      #   run: VERSION="${BUILD_VERSION}" make tag_major_minor
